# Set COMPOSE_PROJECT_NAME environment variable prior to running docker-compose
# to customize identifiers for containers and other resources.

.PHONY: up down

up:
	docker-compose up -d neo4j
down:
	docker-compose down
